### ISSUE TITLE
llVM on win10

### ISSUE THREAD

**Issue by Equinox03** [SchemeImproved/SchemeImproved#1]
CMake Error at CMakeLists.txt:8 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by Eason-S-Lu** [comment]
Will enforce wsl on windows system.
